### ISSUE TITLE
"failed to enable cpuid interception (replay may diverge): No such device" when run "./env-fuzz record gnome-calculator"

### ISSUE THREAD

**Issue by lily11111222** [GJDuck/RRFuzz#6]
Hi, thank you for sharing your tools.
I'm trying to run it on an Ubuntu20.04 of VMWare and of docker and even on a real linux server. It is built fine, but the command "./env-fuzz record gnome-calculator" doesn't work, the error message is 
![image](https://github.com/user-attachments/assets/ae4f84b1-7266-4175-b554-3ded02c746e1)

Any help would be appreciated.
Thanks!

**Comment by GJDuck** [comment]
I assume the GUI did not appear, and it just printed the warning message then "EXIT 1"?

What this means is that the program ran, but something went wrong, causing the program to exit prematurely with an error code.  It would have made a recording of the partial execution, and you should be able to replay it with:

        $ ./env-fuzz replay --log=3

This will also print all recorded syscalls, which may give you a clue as to what went wrong.

As for the "`failed to enable cpuid interception ...`", this is just a warning message.  It just means that the replay may be imperfect due to some nondeterministic instructions that cannot be intercepted.  It depends on the program, since programs that do not use these instructions will not be affected.  And even if the program does use them, it may not diverge anyway.  It really depends.

**Comment by lily11111222** [comment]
Yes, you're right. Thank you very much for your help! I will give it a try.

**Comment by GJDuck** [comment]
Please let me know if it is still not working.  Also, are you using Wayland?

**Comment by lily11111222** [comment]
Okay. Gnome-calculator didn't work yet, but the instruction " ./env-fuzz replay --log=3" gives a lot of log information. I haven't examined in depth yet.
![img_v3_02he_74fa0ca5-9963-4060-b776-72064b7ea84g](https://github.com/user-attachments/assets/cb026811-38a4-47f7-aa95-d0438e5576d5)
![img_v3_02he_1521d944-e2e1-42be-9478-93f3b6346f1g](https://github.com/user-attachments/assets/f0cb6234-adfc-4e2d-ae18-a9fba72732dc)
![img_v3_02he_f850a866-8c1f-4617-bfe7-e01eef1a91dg](https://github.com/user-attachments/assets/0a518554-f85e-403a-a2e5-a352e1ad249b)
...
And this is the result of Ubuntu20.04 on VMWare. I didn't use Wayland.

**Comment by GJDuck** [comment]
Do you have the tail-end of the log?  This will be more useful for finding the problem.

**Comment by lily11111222** [comment]
Yes. I'm not sure these screenshots are enough to pinpoint the problem.
...
![img_v3_02he_d50f6b85-1a85-4c2d-93cd-fe37b82253bg](https://github.com/user-attachments/assets/a6aa6397-a7fc-4e08-9f4f-d77e4fefab6d)
![img_v3_02he_f2c68fe6-48b1-4fde-b138-0e9ffd45fb2g](https://github.com/user-attachments/assets/c60e48e8-0980-4d04-8c4c-58fd685a977f)
![img_v3_02he_4f2265a6-5fbf-4f02-99bd-b9ac60fb8feg](https://github.com/user-attachments/assets/5c0c04de-56e3-43d1-bff3-004c47d549d2)
![image](https://github.com/user-attachments/assets/ffdbc8b7-a017-4728-8239-c61f51544002)

**Comment by GJDuck** [comment]
Thanks for the new log.  Unfortunately it is not too helpful, since it seems the program is just deciding to exit without printing any error message or other clue.  It is reading from `/proc/self/fd` to get a list of the currently open file descriptors, and close them, but this may just be part of the exit routine.

Does `gnome-calculator` run normally (without EnvFuzz) on the system, or does the GUI also not appear?

**Comment by lily11111222** [comment]
`gnome-calculator` can work without EnvFuzz. I tried it with  the simple `gnome-calculator ` instruction. The GUI appeared and it can work.

**Comment by lily11111222** [comment]
I tried again and found that it failed because I run it as `root`, but it worked as a normal user. Perhaps for security reasons, `gnome-calculator` is not allowed to run as `root`. Thank you very much for your help!

**Comment by GJDuck** [comment]
Thanks, this is an important detail.  Actually I realize this was obvious in your first message.

Probably something goes wrong if you attempt to run it as root.  I will try it later myself and see if I can figure it out.

**Comment by GJDuck** [comment]
I tried this myself.  It does not work since (for some reason) `gnome-calculator` will call `fork()` if the user is `root`. EnvFuzz then just follows the child by default, which does not seem to do anything interesting.  However, the following command does display the GUI for me as `root`:

        # ./env-fuzz record --fork=parent gnome-calculator

That said, it is not recommended to run EnvFuzz as `root`.

Since this is likely the problem, I will close this issue.
